### ISSUE TITLE
Documentation for [[x|x]] style function shorthands

### ISSUE THREAD

**Issue by andrewreedy** [Famous/framework#25]
It would be helpful to have some documentation on '[[identity|headerHeight]]' and '[[setter|camel]]' function shorthand (sugar)

**Comment by johnantoni** [comment]
+1

**Comment by matthewtoast** [comment]
Let me know if you think anything needs to be added or clarified:

https://github.com/Famous/framework/blob/develop/docs/api/sugar.md

**Comment by johnantoni** [comment]
Excellent. thanks @matthewtoast

**Comment by andrewreedy** [comment]
Looks great thanks!
