### ISSUE TITLE
Support Animation for Meshes

### ISSUE THREAD

**Issue by tlhunter** [Famous/framework#29]
I spoke with Joseph and it sounds like Famous does not currently allow for animations of meshes (imported OBJ's).

Being able to animate these is a must for high quality game development.

It looks like the [OBJ Standard](http://paulbourke.net/dataformats/obj/) doesn't support animations itself, so a creative solution may be required.

**Comment by matthewtoast** [comment]
Hi @tlhunter -- Should this issue instead be filed under https://github.com/famous/engine? (That is where the core WebGL implementation is located.)

**Comment by tlhunter** [comment]
Good call. Migrated: https://github.com/Famous/engine/issues/333
