### ISSUE TITLE
Docs folder not shared

### ISSUE THREAD

**Issue by agcolom** [Famous/framework#35]
your [README.md](https://github.com/Famous/framework/blob/develop/README.md#windows) makes reference to https://github.com/Famous/framework/blob/develop/docs/windows-installation.md but this doesn't seem to be shared yet. It might be worth either sharing it or adding a warning.

**Comment by matthewtoast** [comment]
Thanks for the note about this! We moved this content but forgot to update the README.

The docs repo is located here:

https://github.com/famous/framework-guides

**Comment by matthewtoast** [comment]
And the live site for docs is here:

http://famous.org/framework/
