### ISSUE TITLE
Events from regular HTML in a tree don't work

### ISSUE THREAD

**Issue by ildarsamit** [Famous/framework#36]
I tried running an example from the website:

http://famous.org/framework/tree.html
Under "Inserting actual HTML"

```
FamousFramework.component('examples',{
      behaviors: {
         '#foo': { //this will work input
            'position':[250,150]
         },
         '#bar': {  // this will not work on input
            'position':[1000,100] 
         }
      },
      events: {
        '#bar': { // this will work on input
            'change': function($payload){
                console.log($payload)
            }
        }
      },
       tree: `<node id="foo">
                <input id="bar" type="range"></input>
              </node>`,
})
```

I get this error: `Uncaught TypeError: Cannot read property 'events' of undefined`
If I replace `#bar` with `input` in the events selector, it doesn't give an error but still doesn't work.
If I replace `#bar` with `#foo`, nothing happens. I'm assuming this means the event doesn't "bubble up" to `#foo` as the website suggests?

**Comment by Imti** [comment]
@ildarsamit There was an API change for the input event name `change`. It's now `input` to match

**Comment by Imti** [comment]
@ildarsamit There was an API change for the input event name `change`. It's been updated to `input` to match the corresponding DOM event `input`.

We'll have to update the docs to match this change.

```
FamousFramework.component('example', {
      behaviors: {
         '#foo': { //this will work input
            'position':[250,150]
         },
         '#bar': {  // this will not work on input
            'position':[1000,100] 
         }
      },
      events: {
        '#bar': { // this will work on input
            'input': function($event){
                console.log($event)
            }
        }
      },
       tree: `
            <node id="foo">
                <input id="bar" type="range"></input>
            </node>
        `
});
```

The change from `change` to `input` above fixes the issue. Also, using the `$event` injectable allows us to receive DOM event objects.

As for not being able to target the `<input>` element by targeting its tag-name seems to be a bug. We'll look into this. Leaving this issue open until resolved.

Thanks for the catch!

**Comment by ildarsamit** [comment]
Awesome, thanks man! Changing the event from `change` to `input` worked.

**Comment by Imti** [comment]
[This commit](https://github.com/Famous/framework/commit/7085bafc5800a119b825f6db281ab9ad63ad91be) should fix the issue.

The problem was that the `input` tag name that we were targeting was being expanded to `famous:events:input` because we also have an `input` event. The solution goes through the events object one level deep (so all the selectors) and doesn't expand them if they match a native html tag.

**Comment by ildarsamit** [comment]
Sweet, thanks.

**Comment by Imti** [comment]
Closing.
