### ISSUE TITLE
sue “Famous Industries”

### ISSUE THREAD

**Issue by flying-sheep** [Famous/framework#74]
Those guys have bought your old domains (famo.us/famous.co) and stolen your “circled φ” logo.

Now that page is plastered with incomprehensible marketing bullshit (micro-apps, wtf) posted leeching off this project’s name and image.

sue them or send a cease-and-desist letter to at least make them stop using the “φ” logo

**Comment by ghost** [comment]
Half of me thinks that your comment is sarcastic.  

In case not: Famous Industries and the company that wrote the famous library are one in the same.  The page at famous.com is their attempt at monetizing the framework.  I'm not going to pass judgement, I didn't contribute any code.

**Comment by flying-sheep** [comment]
oh.

actually i was torn between thinking of that page as being satire or not.

it has huge feel-good stock photos, completely meaningless marketing lingo, and doesn’t link to any useful information at all (e.g. the famous framework website, pricing information, or _what they actually offer_)

> Use micro-apps as mobile landing apps that amplify conversion and increase average order value within your digital marketing campaigns.

“amplify conversion” / “increase average order value” → what.

> - Instagram, twitter and facebook

nice enumeration of social platforms, but what do you mean

> - Email marketing

k. as opposed to what marketing? how does this relate to or interact with “micro-apps”

> - In store promotion

promotion of what? what store? what the what?

> - Digital ads

you don’t say

**Comment by PierreOlivier-LatourTheThird** [comment]
TechCrunch ran an article about this: http://techcrunch.com/2015/11/06/nopen-source/

> Famo.us’ 15 minutes of open source fame have come to an end. JavaScript rendering engine Famo.us has pivoted away from its hardcore open sourced engineering platform which had raised over $31 million. It’s now refocused on commercializing the idea of powerful mobile web apps with a content management system for branded marketing apps.

**Comment by flying-sheep** [comment]
thanks, this explains quite a bit.

what people can take away from this issue is probably that the new landing page is horrible in conveying wtf famous industries does to the layman (it might actually make sense to the target audience of marketing people.

and the the new thing they do is pretty jarring.
